# Generated by Django 4.2.27 on 2026-02-24 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('IdNumber', models.TextField()),
                ('phonenumber', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tennant',
            fields=[
                ('Name', models.TextField(null=True)),
                ('Tennantid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainApp.auser')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('OwnerId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainApp.auser')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('file', models.FileField(upload_to='media/properties')),
                ('PropertyId', models.AutoField(primary_key=True, serialize=False)),
                ('Location', models.CharField(max_length=30)),
                ('Density', models.CharField(max_length=30)),
                ('Rooms', models.IntegerField(default=1)),
                ('Features', models.TextField(default='')),
                ('Avilability', models.BooleanField(default=False)),
                ('ownerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.owner')),
            ],
        ),
    ]
