# Generated by Django 6.0.2 on 2026-02-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='Price',
            field=models.IntegerField(null=True),
        ),
    ]
